### PR TITLE
aggregate console output and run tests sequentially

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Cleanup the output of the build in the Dockerfile:
- print stdout only on package completion to avoid interleaving (using `--event-handler console_cohesion+`)
- run tests sequentially
- nit: fix spelling of `--event-handlers`

Question: do we need the `stdout` of the build at all? maybe displaying only `stderr` would be sufficient ?

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Closing/reopening to trigger travis

**Comment by mikaelarguedas** [comment]
> Question: do we need the stdout of the build at all? maybe displaying only stderr would be sufficient ?

@Karsten1987 how do you feel about that question?

**Comment by Karsten1987** [comment]
I am okay with that. I initially had it print everything to console just for debugging purpose. But I guess `stderr` is sufficient.

**Review by Karsten1987 — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
> I am okay with that. I initially had it print everything to console just for debugging purpose. But I guess stderr is sufficient.

:+1: https://github.com/Karsten1987/roscon2018/pull/11/commits/446b729c02b4f9d894c11e2572c12c8e28568242 changes it to show only stderr for `colcon build`

**Pull request merged**
