### PR TITLE
change empty world to gazebo inbuilt cafe

### PR DESCRIPTION
**Pull request by Karsten1987**
Just an idea, but we could change the default empty world to something a bit more interesting like the inbuilt gazebo cafe. THere are some people walking around and some tables.
Screenshot from 2019-06-06 17-03-25

### CODE REVIEW

**Comment by Karsten1987** [comment]
second to it I changed the alignment of the rqt_gui to split horizontally in order to maximize the camera view
Screenshot from 2019-06-06 17-21-25

**Comment by mikaelarguedas** [comment]
I like the idea:
Is there a way to make sure all the models are downloaded ahead of time in case we need to run this with limited internet connexion ?

> second to it I changed the alignment of the rqt_gui to split horizontally in order to maximize the camera view

:+1:
If this is the same perspective as the one we'll use earlier for `rqt_graph`, I'd recommend defaulting to the opposite (rqt_graph window big, rqt_image_view_small)

**Comment by mikaelarguedas** [comment]
> THere are some people walking around

Is there a magic command to make them walk?

Right now they're doing ... their own thing:
Walking__they_said

**Comment by Karsten1987** [comment]
for me they walk right after opening. @chapulina is there more to it?

**Comment by chapulina** [comment]
Do you see any error messages printed? Maybe it's not loading `libActorPlugin`?

**Comment by chapulina** [comment]
> Is there a way to make sure all the models are downloaded ahead of time

After you download it the first time, the models are cached in `~/.gazebo/models`

**Comment by mikaelarguedas** [comment]
> After you download it the first time, the models are cashed in ~/.gazebo/models

:+1:

> Do you see any error messages printed? Maybe it's not loading libActorPlugin?

I think they were just stuck in a local minima of their obstacle avoidance.

Running it again I saw them walk for ~1min before they got stuck in a different place

**Comment by chapulina** [comment]
> I think they were just stuck in a local minima of their obstacle avoidance.

Ha, totally, I also see them eventually get stuck if I change the real time update rate to 0 (run as fast as possible). It's interesting that both of them always stop at the same time, and sometimes they recover after a while.

**Comment by mikaelarguedas** [comment]
> Ha, totally, I also see them eventually get stuck if I change the real time update rate to 0 (run as fast as possible). It's interesting that both of them always stop at the same time, and sometimes they recover after a while.

well we'll just :crossed_fingers: then

**Review by mikaelarguedas — APPROVED** [review]
we can resize the perspective now or in a later PR.

I'll leave it up to you @Karsten1987

**Comment by Karsten1987** [comment]
I actually believe resizing to a fix size doesn't make much sense, because in the end it depends on your screen and resolution etc. It should be fairly trivial to resize it on the fly.

**Pull request merged**
