### PR TITLE
try using ros2_ci repo

### PR DESCRIPTION
**Pull request by mikaelarguedas**
@Karsten1987 here's an example of externalizing the CI logic to a single repo and import it for CI purposes. All that's needed is to use this standard .travis.yml file in all the repos that want to run CI on ROS2 (crystal and / or nightly builds). The approach is similar to industrial_ci but much more basic.
Does that match what you were describing in https://github.com/Karsten1987/roscon2018/pull/13#discussion_r264469923 ?

### CODE REVIEW

**Comment by Karsten1987** [comment]
can this be closed?

**Comment by mikaelarguedas** [comment]
While I didnt get back to it as I was focusing on getting the ros2:nightly image ready for use in here. I still believe there is value in centralizing CI resources. Current CI is fine for now, but will need to be able to run against both master and Dashing starting next month.

So I'd rather leave this open and iterate on it later on when we need it

An example of how the current approach falls short if that the dependencies specified in `workspace.repos` are built in the same workspace as this repo. So to not have CI result impacted by upstream test failures we would need to either build them in separate workspace of use a whitelist/blacklist approach when running the tests

**Comment by mikaelarguedas** [comment]
CI needs https://github.com/colcon/colcon-core/pull/179 before coming back green.

It'll work on the `gazebo` branch as the underlay is not empty. We can use an isolated install space for the underlay in the meantime

**Comment by mikaelarguedas** [comment]
> We can use an isolated install space for the underlay in the meantime

Implemented that in the meantime and tracked it here https://github.com/mikaelarguedas/ros2ci/pull/11

CI is now green

**Pull request merged**
